<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('districts')->delete();

        \DB::table('districts')->insert([
            0 => [
                'id' => 1,
                'type' => 'ស្រុក',
                'code' => '102',
                'name_kh' => 'មង្គលបូរី',
                'name_en' => 'Mongkol Borei',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'type' => 'ស្រុក',
                'code' => '103',
                'name_kh' => 'ភ្នំស្រុក',
                'name_en' => 'Phnum Srok',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'type' => 'ស្រុក',
                'code' => '104',
                'name_kh' => 'ព្រះនេត្រព្រះ',
                'name_en' => 'Preah Netr Preah',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'type' => 'ស្រុក',
                'code' => '105',
                'name_kh' => 'អូរជ្រៅ',
                'name_en' => 'Ou Chrov',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'type' => 'ក្រុង',
                'code' => '106',
                'name_kh' => 'សិរីសោភ័ណ',
                'name_en' => 'Serei Saophoan',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'type' => 'ស្រុក',
                'code' => '107',
                'name_kh' => 'ថ្មពួក',
                'name_en' => 'Thma Puok',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 7,
                'type' => 'ស្រុក',
                'code' => '108',
                'name_kh' => 'ស្វាយចេក',
                'name_en' => 'Svay Chek',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 8,
                'type' => 'ស្រុក',
                'code' => '109',
                'name_kh' => 'ម៉ាឡៃ',
                'name_en' => 'Malai',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 9,
                'type' => 'ក្រុង',
                'code' => '110',
                'name_kh' => 'ប៉ោយប៉ែត',
                'name_en' => 'Paoy Paet',
                'province_id' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'type' => 'ស្រុក',
                'code' => '201',
                'name_kh' => 'បាណន់',
                'name_en' => 'Banan',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 11,
                'type' => 'ស្រុក',
                'code' => '202',
                'name_kh' => 'ថ្មគោល',
                'name_en' => 'Thma Koul',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 12,
                'type' => 'ក្រុង',
                'code' => '203',
                'name_kh' => 'បាត់ដំបង',
                'name_en' => 'Battambang',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 13,
                'type' => 'ស្រុក',
                'code' => '204',
                'name_kh' => 'បវេល',
                'name_en' => 'Bavel',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            13 => [
                'id' => 14,
                'type' => 'ស្រុក',
                'code' => '205',
                'name_kh' => 'ឯកភ្នំ',
                'name_en' => 'Aek Phnum',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            14 => [
                'id' => 15,
                'type' => 'ស្រុក',
                'code' => '206',
                'name_kh' => 'មោងឫស្សី',
                'name_en' => 'Moung Ruessei',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            15 => [
                'id' => 16,
                'type' => 'ស្រុក',
                'code' => '207',
                'name_kh' => 'រតនមណ្ឌល',
                'name_en' => 'Rotonak Mondol',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            16 => [
                'id' => 17,
                'type' => 'ស្រុក',
                'code' => '208',
                'name_kh' => 'សង្កែ',
                'name_en' => 'Sangkae',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            17 => [
                'id' => 18,
                'type' => 'ស្រុក',
                'code' => '209',
                'name_kh' => 'សំឡូត',
                'name_en' => 'Samlout',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'id' => 19,
                'type' => 'ស្រុក',
                'code' => '210',
                'name_kh' => 'សំពៅលូន',
                'name_en' => 'Sampov Lun',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            19 => [
                'id' => 20,
                'type' => 'ស្រុក',
                'code' => '211',
                'name_kh' => 'ភ្នំព្រឹក',
                'name_en' => 'Phnum Proek',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            20 => [
                'id' => 21,
                'type' => 'ស្រុក',
                'code' => '212',
                'name_kh' => 'កំរៀង',
                'name_en' => 'Kamrieng',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            21 => [
                'id' => 22,
                'type' => 'ស្រុក',
                'code' => '213',
                'name_kh' => 'គាស់ក្រឡ',
                'name_en' => 'Koas Krala',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            22 => [
                'id' => 23,
                'type' => 'ស្រុក',
                'code' => '214',
                'name_kh' => 'រុក្ខគិរី',
                'name_en' => 'Rukh Kiri',
                'province_id' => 2,
                'created_at' => null,
                'updated_at' => null,
            ],
            23 => [
                'id' => 24,
                'type' => 'ស្រុក',
                'code' => '301',
                'name_kh' => 'បាធាយ',
                'name_en' => 'Batheay',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            24 => [
                'id' => 25,
                'type' => 'ស្រុក',
                'code' => '302',
                'name_kh' => 'ចំការលើ',
                'name_en' => 'Chamkar Leu',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            25 => [
                'id' => 26,
                'type' => 'ស្រុក',
                'code' => '303',
                'name_kh' => 'ជើងព្រៃ',
                'name_en' => 'Cheung Prey',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            26 => [
                'id' => 27,
                'type' => 'ក្រុង',
                'code' => '305',
                'name_kh' => 'កំពង់ចាម',
                'name_en' => 'Kampong Cham',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            27 => [
                'id' => 28,
                'type' => 'ស្រុក',
                'code' => '306',
                'name_kh' => 'កំពង់សៀម',
                'name_en' => 'Kampong Siem',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            28 => [
                'id' => 29,
                'type' => 'ស្រុក',
                'code' => '307',
                'name_kh' => 'កងមាស',
                'name_en' => 'Kang Meas',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            29 => [
                'id' => 30,
                'type' => 'ស្រុក',
                'code' => '308',
                'name_kh' => 'កោះសូទិន',
                'name_en' => 'Kaoh Soutin',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            30 => [
                'id' => 31,
                'type' => 'ស្រុក',
                'code' => '313',
                'name_kh' => 'ព្រៃឈរ',
                'name_en' => 'Prey Chhor',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            31 => [
                'id' => 32,
                'type' => 'ស្រុក',
                'code' => '314',
                'name_kh' => 'ស្រីសន្ធរ',
                'name_en' => 'Srei Santhor',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            32 => [
                'id' => 33,
                'type' => 'ស្រុក',
                'code' => '315',
                'name_kh' => 'ស្ទឹងត្រង់',
                'name_en' => 'Stueng Trang',
                'province_id' => 3,
                'created_at' => null,
                'updated_at' => null,
            ],
            33 => [
                'id' => 34,
                'type' => 'ស្រុក',
                'code' => '401',
                'name_kh' => 'បរិបូណ៌',
                'name_en' => 'Baribour',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            34 => [
                'id' => 35,
                'type' => 'ស្រុក',
                'code' => '402',
                'name_kh' => 'ជលគីរី',
                'name_en' => 'Chol Kiri',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            35 => [
                'id' => 36,
                'type' => 'ក្រុង',
                'code' => '403',
                'name_kh' => 'កំពង់ឆ្នាំង',
                'name_en' => 'Kampong Chhnang',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            36 => [
                'id' => 37,
                'type' => 'ស្រុក',
                'code' => '404',
                'name_kh' => 'កំពង់លែង',
                'name_en' => 'Kampong Leaeng',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            37 => [
                'id' => 38,
                'type' => 'ស្រុក',
                'code' => '405',
                'name_kh' => 'កំពង់ត្រឡាច',
                'name_en' => 'Kampong Tralach',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            38 => [
                'id' => 39,
                'type' => 'ស្រុក',
                'code' => '406',
                'name_kh' => 'រលាប្អៀរ',
                'name_en' => 'Rolea B\'ier',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            39 => [
                'id' => 40,
                'type' => 'ស្រុក',
                'code' => '407',
                'name_kh' => 'សាមគ្គីមានជ័យ',
                'name_en' => 'Sameakki Mean Chey',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            40 => [
                'id' => 41,
                'type' => 'ស្រុក',
                'code' => '408',
                'name_kh' => 'ទឹកផុស',
                'name_en' => 'Tuek Phos',
                'province_id' => 4,
                'created_at' => null,
                'updated_at' => null,
            ],
            41 => [
                'id' => 42,
                'type' => 'ស្រុក',
                'code' => '501',
                'name_kh' => 'បរសេដ្ឋ',
                'name_en' => 'Basedth',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            42 => [
                'id' => 43,
                'type' => 'ក្រុង',
                'code' => '502',
                'name_kh' => 'ច្បារមន',
                'name_en' => 'Chbar Mon',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            43 => [
                'id' => 44,
                'type' => 'ស្រុក',
                'code' => '503',
                'name_kh' => 'គងពិសី',
                'name_en' => 'Kong Pisei',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            44 => [
                'id' => 45,
                'type' => 'ស្រុក',
                'code' => '504',
                'name_kh' => 'ឱរ៉ាល់',
                'name_en' => 'Aoral',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            45 => [
                'id' => 46,
                'type' => 'ស្រុក',
                'code' => '505',
                'name_kh' => 'ឧដុង្គ',
                'name_en' => 'Odongk',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            46 => [
                'id' => 47,
                'type' => 'ស្រុក',
                'code' => '506',
                'name_kh' => 'ភ្នំស្រួច',
                'name_en' => 'Phnum Sruoch',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            47 => [
                'id' => 48,
                'type' => 'ស្រុក',
                'code' => '507',
                'name_kh' => 'សំរោងទង',
                'name_en' => 'Samraong Tong',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            48 => [
                'id' => 49,
                'type' => 'ស្រុក',
                'code' => '508',
                'name_kh' => 'ថ្ពង',
                'name_en' => 'Thpong',
                'province_id' => 5,
                'created_at' => null,
                'updated_at' => null,
            ],
            49 => [
                'id' => 50,
                'type' => 'ស្រុក',
                'code' => '601',
                'name_kh' => 'បារាយណ៍',
                'name_en' => 'Baray',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            50 => [
                'id' => 51,
                'type' => 'ស្រុក',
                'code' => '602',
                'name_kh' => 'កំពង់ស្វាយ',
                'name_en' => 'Kampong Svay',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            51 => [
                'id' => 52,
                'type' => 'ក្រុង',
                'code' => '603',
                'name_kh' => 'ស្ទឹងសែន',
                'name_en' => 'Stueng Saen',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            52 => [
                'id' => 53,
                'type' => 'ស្រុក',
                'code' => '604',
                'name_kh' => 'ប្រាសាទបល្ល័ង្គ',
                'name_en' => 'Prasat Ballangk',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            53 => [
                'id' => 54,
                'type' => 'ស្រុក',
                'code' => '605',
                'name_kh' => 'ប្រាសាទសំបូរ',
                'name_en' => 'Prasat Sambour',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            54 => [
                'id' => 55,
                'type' => 'ស្រុក',
                'code' => '606',
                'name_kh' => 'សណ្ដាន់',
                'name_en' => 'Sandan',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            55 => [
                'id' => 56,
                'type' => 'ស្រុក',
                'code' => '607',
                'name_kh' => 'សន្ទុក',
                'name_en' => 'Santuk',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            56 => [
                'id' => 57,
                'type' => 'ស្រុក',
                'code' => '608',
                'name_kh' => 'ស្ទោង',
                'name_en' => 'Stoung',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            57 => [
                'id' => 58,
                'type' => 'ស្រុក',
                'code' => '609',
                'name_kh' => 'តាំងគោក',
                'name_en' => 'Taing Kouk',
                'province_id' => 6,
                'created_at' => null,
                'updated_at' => null,
            ],
            58 => [
                'id' => 59,
                'type' => 'ស្រុក',
                'code' => '701',
                'name_kh' => 'អង្គរជ័យ',
                'name_en' => 'Angkor Chey',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            59 => [
                'id' => 60,
                'type' => 'ស្រុក',
                'code' => '702',
                'name_kh' => 'បន្ទាយមាស',
                'name_en' => 'Banteay Meas',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            60 => [
                'id' => 61,
                'type' => 'ស្រុក',
                'code' => '703',
                'name_kh' => 'ឈូក',
                'name_en' => 'Chhuk',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            61 => [
                'id' => 62,
                'type' => 'ស្រុក',
                'code' => '704',
                'name_kh' => 'ជុំគិរី',
                'name_en' => 'Chum Kiri',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            62 => [
                'id' => 63,
                'type' => 'ស្រុក',
                'code' => '705',
                'name_kh' => 'ដងទង់',
                'name_en' => 'Dang Tong',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            63 => [
                'id' => 64,
                'type' => 'ស្រុក',
                'code' => '706',
                'name_kh' => 'កំពង់ត្រាច',
                'name_en' => 'Kampong Trach',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            64 => [
                'id' => 65,
                'type' => 'ស្រុក',
                'code' => '707',
                'name_kh' => 'ទឹកឈូ',
                'name_en' => 'Tuek Chhou',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            65 => [
                'id' => 66,
                'type' => 'ក្រុង',
                'code' => '708',
                'name_kh' => 'កំពត',
                'name_en' => 'Kampot',
                'province_id' => 7,
                'created_at' => null,
                'updated_at' => null,
            ],
            66 => [
                'id' => 67,
                'type' => 'ស្រុក',
                'code' => '801',
                'name_kh' => 'កណ្ដាលស្ទឹង',
                'name_en' => 'Kandal Stueng',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            67 => [
                'id' => 68,
                'type' => 'ស្រុក',
                'code' => '802',
                'name_kh' => 'កៀនស្វាយ',
                'name_en' => 'Kien Svay',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            68 => [
                'id' => 69,
                'type' => 'ស្រុក',
                'code' => '803',
                'name_kh' => 'ខ្សាច់កណ្ដាល',
                'name_en' => 'Khsach Kandal',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            69 => [
                'id' => 70,
                'type' => 'ស្រុក',
                'code' => '804',
                'name_kh' => 'កោះធំ',
                'name_en' => 'Kaoh Thum',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            70 => [
                'id' => 71,
                'type' => 'ស្រុក',
                'code' => '805',
                'name_kh' => 'លើកដែក',
                'name_en' => 'Leuk Daek',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            71 => [
                'id' => 72,
                'type' => 'ស្រុក',
                'code' => '806',
                'name_kh' => 'ល្វាឯម',
                'name_en' => 'Lvea Aem',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            72 => [
                'id' => 73,
                'type' => 'ស្រុក',
                'code' => '807',
                'name_kh' => 'មុខកំពូល',
                'name_en' => 'Mukh Kampul',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            73 => [
                'id' => 74,
                'type' => 'ស្រុក',
                'code' => '808',
                'name_kh' => 'អង្គស្នួល',
                'name_en' => 'Angk Snuol',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            74 => [
                'id' => 75,
                'type' => 'ស្រុក',
                'code' => '809',
                'name_kh' => 'ពញាឮ',
                'name_en' => 'Ponhea Lueu',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            75 => [
                'id' => 76,
                'type' => 'ស្រុក',
                'code' => '810',
                'name_kh' => 'ស្អាង',
                'name_en' => 'S\'ang',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            76 => [
                'id' => 77,
                'type' => 'ក្រុង',
                'code' => '811',
                'name_kh' => 'តាខ្មៅ',
                'name_en' => 'Ta Khmau',
                'province_id' => 8,
                'created_at' => null,
                'updated_at' => null,
            ],
            77 => [
                'id' => 78,
                'type' => 'ស្រុក',
                'code' => '901',
                'name_kh' => 'បុទុមសាគរ',
                'name_en' => 'Botum Sakor',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            78 => [
                'id' => 79,
                'type' => 'ស្រុក',
                'code' => '902',
                'name_kh' => 'គិរីសាគរ',
                'name_en' => 'Kiri Sakor',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            79 => [
                'id' => 80,
                'type' => 'ស្រុក',
                'code' => '903',
                'name_kh' => 'កោះកុង',
                'name_en' => 'Kaoh Kong',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            80 => [
                'id' => 81,
                'type' => 'ក្រុង',
                'code' => '904',
                'name_kh' => 'ខេមរភូមិន្ទ',
                'name_en' => 'Khemara Phoumin',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            81 => [
                'id' => 82,
                'type' => 'ស្រុក',
                'code' => '905',
                'name_kh' => 'មណ្ឌលសីមា',
                'name_en' => 'Mondol Seima',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            82 => [
                'id' => 83,
                'type' => 'ស្រុក',
                'code' => '906',
                'name_kh' => 'ស្រែ អំបិល',
                'name_en' => 'Srae Ambel',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            83 => [
                'id' => 84,
                'type' => 'ស្រុក',
                'code' => '907',
                'name_kh' => 'ថ្មបាំង',
                'name_en' => 'Thma Bang',
                'province_id' => 9,
                'created_at' => null,
                'updated_at' => null,
            ],
            84 => [
                'id' => 85,
                'type' => 'ស្រុក',
                'code' => '1001',
                'name_kh' => 'ឆ្លូង',
                'name_en' => 'Chhloung',
                'province_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            85 => [
                'id' => 86,
                'type' => 'ក្រុង',
                'code' => '1002',
                'name_kh' => 'ក្រចេះ',
                'name_en' => 'Kracheh',
                'province_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            86 => [
                'id' => 87,
                'type' => 'ស្រុក',
                'code' => '1003',
                'name_kh' => 'ព្រែកប្រសព្វ',
                'name_en' => 'Prek Prasab',
                'province_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            87 => [
                'id' => 88,
                'type' => 'ស្រុក',
                'code' => '1004',
                'name_kh' => 'សំបូរ',
                'name_en' => 'Sambour',
                'province_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            88 => [
                'id' => 89,
                'type' => 'ស្រុក',
                'code' => '1005',
                'name_kh' => 'ស្នួល',
                'name_en' => 'Snuol',
                'province_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            89 => [
                'id' => 90,
                'type' => 'ស្រុក',
                'code' => '1006',
                'name_kh' => 'ចិត្របុរី',
                'name_en' => 'Chetr Borei',
                'province_id' => 10,
                'created_at' => null,
                'updated_at' => null,
            ],
            90 => [
                'id' => 91,
                'type' => 'ស្រុក',
                'code' => '1101',
                'name_kh' => 'កែវសីមា',
                'name_en' => 'Kaev Seima',
                'province_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            91 => [
                'id' => 92,
                'type' => 'ស្រុក',
                'code' => '1102',
                'name_kh' => 'កោះញែក',
                'name_en' => 'Kaoh Nheaek',
                'province_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            92 => [
                'id' => 93,
                'type' => 'ស្រុក',
                'code' => '1103',
                'name_kh' => 'អូររាំង',
                'name_en' => 'Ou Reang',
                'province_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            93 => [
                'id' => 94,
                'type' => 'ស្រុក',
                'code' => '1104',
                'name_kh' => 'ពេជ្រាដា',
                'name_en' => 'Pech Chreada',
                'province_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            94 => [
                'id' => 95,
                'type' => 'ក្រុង',
                'code' => '1105',
                'name_kh' => 'សែនមនោរម្យ',
                'name_en' => 'Saen Monourom',
                'province_id' => 11,
                'created_at' => null,
                'updated_at' => null,
            ],
            95 => [
                'id' => 96,
                'type' => 'ខណ្ឌ',
                'code' => '1201',
                'name_kh' => 'ចំការមន',
                'name_en' => 'Chamkar Mon',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            96 => [
                'id' => 97,
                'type' => 'ខណ្ឌ',
                'code' => '1202',
                'name_kh' => 'ដូនពេញ',
                'name_en' => 'Doun Penh',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            97 => [
                'id' => 98,
                'type' => 'ខណ្ឌ',
                'code' => '1203',
                'name_kh' => '៧មករា',
                'name_en' => 'Prampir Meakkakra',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            98 => [
                'id' => 99,
                'type' => 'ខណ្ឌ',
                'code' => '1204',
                'name_kh' => 'ទួលគោក',
                'name_en' => 'Tuol Kouk',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            99 => [
                'id' => 100,
                'type' => 'ខណ្ឌ',
                'code' => '1205',
                'name_kh' => 'ដង្កោ',
                'name_en' => 'Dangkao',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            100 => [
                'id' => 101,
                'type' => 'ខណ្ឌ',
                'code' => '1206',
                'name_kh' => 'មានជ័យ',
                'name_en' => 'Mean Chey',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            101 => [
                'id' => 102,
                'type' => 'ខណ្ឌ',
                'code' => '1207',
                'name_kh' => 'ឫស្សីកែវ',
                'name_en' => 'Russey Keo',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            102 => [
                'id' => 103,
                'type' => 'ខណ្ឌ',
                'code' => '1208',
                'name_kh' => 'សែនសុខ',
                'name_en' => 'Saensokh',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            103 => [
                'id' => 104,
                'type' => 'ខណ្ឌ',
                'code' => '1209',
                'name_kh' => 'ពោធិ៍សែនជ័យ',
                'name_en' => 'Pur SenChey',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            104 => [
                'id' => 105,
                'type' => 'ខណ្ឌ',
                'code' => '1210',
                'name_kh' => 'ជ្រោយចង្វារ',
                'name_en' => 'Chraoy Chongvar',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            105 => [
                'id' => 106,
                'type' => 'ខណ្ឌ',
                'code' => '1211',
                'name_kh' => 'ព្រែកព្នៅ',
                'name_en' => 'Praek Pnov',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            106 => [
                'id' => 107,
                'type' => 'ខណ្ឌ',
                'code' => '1212',
                'name_kh' => 'ច្បារអំពៅ',
                'name_en' => 'Chbar Ampov',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            107 => [
                'id' => 108,
                'type' => 'ខណ្ឌ',
                'code' => '1213',
                'name_kh' => 'បឹងកេងកង',
                'name_en' => 'Boeng Keng Kang',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            108 => [
                'id' => 109,
                'type' => 'ខណ្ឌ',
                'code' => '1214',
                'name_kh' => 'កំបូល',
                'name_en' => 'Kamboul',
                'province_id' => 12,
                'created_at' => null,
                'updated_at' => null,
            ],
            109 => [
                'id' => 110,
                'type' => 'ស្រុក',
                'code' => '1301',
                'name_kh' => 'ជ័យសែន',
                'name_en' => 'Chey Saen',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            110 => [
                'id' => 111,
                'type' => 'ស្រុក',
                'code' => '1302',
                'name_kh' => 'ឆែប',
                'name_en' => 'Chhaeb',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            111 => [
                'id' => 112,
                'type' => 'ស្រុក',
                'code' => '1303',
                'name_kh' => 'ជាំក្សាន្ដ',
                'name_en' => 'Choam Ksant',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            112 => [
                'id' => 113,
                'type' => 'ស្រុក',
                'code' => '1304',
                'name_kh' => 'គូលែន',
                'name_en' => 'Kuleaen',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            113 => [
                'id' => 114,
                'type' => 'ស្រុក',
                'code' => '1305',
                'name_kh' => 'រវៀង',
                'name_en' => 'Rovieng',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            114 => [
                'id' => 115,
                'type' => 'ស្រុក',
                'code' => '1306',
                'name_kh' => 'សង្គមថ្មី',
                'name_en' => 'Sangkum Thmei',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            115 => [
                'id' => 116,
                'type' => 'ស្រុក',
                'code' => '1307',
                'name_kh' => 'ត្បែងមានជ័យ',
                'name_en' => 'Tbaeng Mean Chey',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            116 => [
                'id' => 117,
                'type' => 'ក្រុង',
                'code' => '1308',
                'name_kh' => 'ព្រះវិហារ',
                'name_en' => 'Preah Vihear',
                'province_id' => 13,
                'created_at' => null,
                'updated_at' => null,
            ],
            117 => [
                'id' => 118,
                'type' => 'ស្រុក',
                'code' => '1401',
                'name_kh' => 'បាភ្នំ',
                'name_en' => 'Ba Phnum',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            118 => [
                'id' => 119,
                'type' => 'ស្រុក',
                'code' => '1402',
                'name_kh' => 'កំចាយមារ',
                'name_en' => 'Kamchay Mear',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            119 => [
                'id' => 120,
                'type' => 'ស្រុក',
                'code' => '1403',
                'name_kh' => 'កំពង់ត្របែក',
                'name_en' => 'Kampong Trabaek',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            120 => [
                'id' => 121,
                'type' => 'ស្រុក',
                'code' => '1404',
                'name_kh' => 'កញ្ជ្រៀច',
                'name_en' => 'Kanhchriech',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            121 => [
                'id' => 122,
                'type' => 'ស្រុក',
                'code' => '1405',
                'name_kh' => 'មេសាង',
                'name_en' => 'Me Sang',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            122 => [
                'id' => 123,
                'type' => 'ស្រុក',
                'code' => '1406',
                'name_kh' => 'ពាមជរ',
                'name_en' => 'Peam Chor',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            123 => [
                'id' => 124,
                'type' => 'ស្រុក',
                'code' => '1407',
                'name_kh' => 'ពាមរក៍',
                'name_en' => 'Peam Ro',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            124 => [
                'id' => 125,
                'type' => 'ស្រុក',
                'code' => '1408',
                'name_kh' => 'ពារាំង',
                'name_en' => 'Pea Reang',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            125 => [
                'id' => 126,
                'type' => 'ស្រុក',
                'code' => '1409',
                'name_kh' => 'ព្រះស្ដេច',
                'name_en' => 'Preah Sdach',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            126 => [
                'id' => 127,
                'type' => 'ក្រុង',
                'code' => '1410',
                'name_kh' => 'ព្រៃវែង',
                'name_en' => 'Prey Veng',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            127 => [
                'id' => 128,
                'type' => 'ស្រុក',
                'code' => '1411',
                'name_kh' => 'ពោធិ៍រៀង',
                'name_en' => 'Pur Rieng',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            128 => [
                'id' => 129,
                'type' => 'ស្រុក',
                'code' => '1412',
                'name_kh' => 'ស៊ីធរកណ្ដាល',
                'name_en' => 'Sithor Kandal',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            129 => [
                'id' => 130,
                'type' => 'ស្រុក',
                'code' => '1413',
                'name_kh' => 'ស្វាយអន្ទរ',
                'name_en' => 'Svay Antor',
                'province_id' => 14,
                'created_at' => null,
                'updated_at' => null,
            ],
            130 => [
                'id' => 131,
                'type' => 'ស្រុក',
                'code' => '1501',
                'name_kh' => 'បាកាន',
                'name_en' => 'Bakan',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            131 => [
                'id' => 132,
                'type' => 'ស្រុក',
                'code' => '1502',
                'name_kh' => 'កណ្ដៀង',
                'name_en' => 'Kandieng',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            132 => [
                'id' => 133,
                'type' => 'ស្រុក',
                'code' => '1503',
                'name_kh' => 'ក្រគរ',
                'name_en' => 'Krakor',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            133 => [
                'id' => 134,
                'type' => 'ស្រុក',
                'code' => '1504',
                'name_kh' => 'ភ្នំក្រវ៉ាញ',
                'name_en' => 'Phnum Kravanh',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            134 => [
                'id' => 135,
                'type' => 'ក្រុង',
                'code' => '1505',
                'name_kh' => 'ពោធិ៍សាត់',
                'name_en' => 'Pursat',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            135 => [
                'id' => 136,
                'type' => 'ស្រុក',
                'code' => '1506',
                'name_kh' => 'វាលវែង',
                'name_en' => 'Veal Veaeng',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            136 => [
                'id' => 137,
                'type' => 'ស្រុក',
                'code' => '1507',
                'name_kh' => 'តាលោសែនជ័យ',
                'name_en' => 'Ta Lou Senchey',
                'province_id' => 15,
                'created_at' => null,
                'updated_at' => null,
            ],
            137 => [
                'id' => 138,
                'type' => 'ស្រុក',
                'code' => '1601',
                'name_kh' => 'អណ្ដូងមាស',
                'name_en' => 'Andoung Meas',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            138 => [
                'id' => 139,
                'type' => 'ក្រុង',
                'code' => '1602',
                'name_kh' => 'បានលុង',
                'name_en' => 'Ban Lung',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            139 => [
                'id' => 140,
                'type' => 'ស្រុក',
                'code' => '1603',
                'name_kh' => 'បរកែវ',
                'name_en' => 'Bar Kaev',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            140 => [
                'id' => 141,
                'type' => 'ស្រុក',
                'code' => '1604',
                'name_kh' => 'កូនមុំ',
                'name_en' => 'Koun Mom',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            141 => [
                'id' => 142,
                'type' => 'ស្រុក',
                'code' => '1605',
                'name_kh' => 'លំផាត់',
                'name_en' => 'Lumphat',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            142 => [
                'id' => 143,
                'type' => 'ស្រុក',
                'code' => '1606',
                'name_kh' => 'អូរជុំ',
                'name_en' => 'Ou Chum',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            143 => [
                'id' => 144,
                'type' => 'ស្រុក',
                'code' => '1607',
                'name_kh' => 'អូរយ៉ាដាវ',
                'name_en' => 'Ou Ya Dav',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            144 => [
                'id' => 145,
                'type' => 'ស្រុក',
                'code' => '1608',
                'name_kh' => 'តាវែង',
                'name_en' => 'Ta Veaeng',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            145 => [
                'id' => 146,
                'type' => 'ស្រុក',
                'code' => '1609',
                'name_kh' => 'វើនសៃ',
                'name_en' => 'Veun Sai',
                'province_id' => 16,
                'created_at' => null,
                'updated_at' => null,
            ],
            146 => [
                'id' => 147,
                'type' => 'ស្រុក',
                'code' => '1701',
                'name_kh' => 'អង្គរជុំ',
                'name_en' => 'Angkor Chum',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            147 => [
                'id' => 148,
                'type' => 'ស្រុក',
                'code' => '1702',
                'name_kh' => 'អង្គរធំ',
                'name_en' => 'Angkor Thum',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            148 => [
                'id' => 149,
                'type' => 'ស្រុក',
                'code' => '1703',
                'name_kh' => 'បន្ទាយស្រី',
                'name_en' => 'Banteay Srei',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            149 => [
                'id' => 150,
                'type' => 'ស្រុក',
                'code' => '1704',
                'name_kh' => 'ជីក្រែង',
                'name_en' => 'Chi Kraeng',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            150 => [
                'id' => 151,
                'type' => 'ស្រុក',
                'code' => '1706',
                'name_kh' => 'ក្រឡាញ់',
                'name_en' => 'Kralanh',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            151 => [
                'id' => 152,
                'type' => 'ស្រុក',
                'code' => '1707',
                'name_kh' => 'ពួក',
                'name_en' => 'Puok',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            152 => [
                'id' => 153,
                'type' => 'ស្រុក',
                'code' => '1709',
                'name_kh' => 'ប្រាសាទបាគង',
                'name_en' => 'Prasat Bakong',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            153 => [
                'id' => 154,
                'type' => 'ក្រុង',
                'code' => '1710',
                'name_kh' => 'សៀមរាប',
                'name_en' => 'Siem Reap',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            154 => [
                'id' => 155,
                'type' => 'ស្រុក',
                'code' => '1711',
                'name_kh' => 'សូទ្រនិគម',
                'name_en' => 'Soutr Nikom',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            155 => [
                'id' => 156,
                'type' => 'ស្រុក',
                'code' => '1712',
                'name_kh' => 'ស្រីស្នំ',
                'name_en' => 'Srei Snam',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            156 => [
                'id' => 157,
                'type' => 'ស្រុក',
                'code' => '1713',
                'name_kh' => 'ស្វាយលើ',
                'name_en' => 'Svay Leu',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            157 => [
                'id' => 158,
                'type' => 'ស្រុក',
                'code' => '1714',
                'name_kh' => 'វ៉ារិន',
                'name_en' => 'Varin',
                'province_id' => 17,
                'created_at' => null,
                'updated_at' => null,
            ],
            158 => [
                'id' => 159,
                'type' => 'ក្រុង',
                'code' => '1801',
                'name_kh' => 'ព្រះសីហនុ',
                'name_en' => 'Preah Sihanouk',
                'province_id' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            159 => [
                'id' => 160,
                'type' => 'ស្រុក',
                'code' => '1802',
                'name_kh' => 'ព្រៃនប់',
                'name_en' => 'Prey Nob',
                'province_id' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            160 => [
                'id' => 161,
                'type' => 'ស្រុក',
                'code' => '1803',
                'name_kh' => 'ស្ទឹងហាវ',
                'name_en' => 'Stueng Hav',
                'province_id' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            161 => [
                'id' => 162,
                'type' => 'ស្រុក',
                'code' => '1804',
                'name_kh' => 'កំពង់សីលា',
                'name_en' => 'Kampong Seila',
                'province_id' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            162 => [
                'id' => 163,
                'type' => 'ក្រុង',
                'code' => '1805',
                'name_kh' => 'កោះរ៉ុង',
                'name_en' => 'Kaoh Rung',
                'province_id' => 18,
                'created_at' => null,
                'updated_at' => null,
            ],
            163 => [
                'id' => 164,
                'type' => 'ស្រុក',
                'code' => '1901',
                'name_kh' => 'សេសាន',
                'name_en' => 'Sesan',
                'province_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            164 => [
                'id' => 165,
                'type' => 'ស្រុក',
                'code' => '1902',
                'name_kh' => 'សៀមបូក',
                'name_en' => 'Siem Bouk',
                'province_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            165 => [
                'id' => 166,
                'type' => 'ស្រុក',
                'code' => '1903',
                'name_kh' => 'សៀមប៉ាង',
                'name_en' => 'Siem Pang',
                'province_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            166 => [
                'id' => 167,
                'type' => 'ក្រុង',
                'code' => '1904',
                'name_kh' => 'ស្ទឹងត្រែង',
                'name_en' => 'Stueng Traeng',
                'province_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            167 => [
                'id' => 168,
                'type' => 'ស្រុក',
                'code' => '1905',
                'name_kh' => 'ថាឡាបរិវ៉ាត់',
                'name_en' => 'Thala Barivat',
                'province_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            168 => [
                'id' => 169,
                'type' => 'ស្រុក',
                'code' => '1906',
                'name_kh' => 'បុរីអូរស្វាយសែនជ័យ',
                'name_en' => 'Borei Ou Svay Senchey',
                'province_id' => 19,
                'created_at' => null,
                'updated_at' => null,
            ],
            169 => [
                'id' => 170,
                'type' => 'ស្រុក',
                'code' => '2001',
                'name_kh' => 'ចន្ទ្រា',
                'name_en' => 'Chantrea',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            170 => [
                'id' => 171,
                'type' => 'ស្រុក',
                'code' => '2002',
                'name_kh' => 'កំពង់រោទិ៍',
                'name_en' => 'Kampong Rou',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            171 => [
                'id' => 172,
                'type' => 'ស្រុក',
                'code' => '2003',
                'name_kh' => 'រំដួល',
                'name_en' => 'Rumduol',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            172 => [
                'id' => 173,
                'type' => 'ស្រុក',
                'code' => '2004',
                'name_kh' => 'រមាសហែក',
                'name_en' => 'Romeas Haek',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            173 => [
                'id' => 174,
                'type' => 'ស្រុក',
                'code' => '2005',
                'name_kh' => 'ស្វាយជ្រំ',
                'name_en' => 'Svay Chrum',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            174 => [
                'id' => 175,
                'type' => 'ក្រុង',
                'code' => '2006',
                'name_kh' => 'ស្វាយរៀង',
                'name_en' => 'Svay Rieng',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            175 => [
                'id' => 176,
                'type' => 'ស្រុក',
                'code' => '2007',
                'name_kh' => 'ស្វាយទាប',
                'name_en' => 'Svay Teab',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            176 => [
                'id' => 177,
                'type' => 'ក្រុង',
                'code' => '2008',
                'name_kh' => 'បាវិត',
                'name_en' => 'Bavet',
                'province_id' => 20,
                'created_at' => null,
                'updated_at' => null,
            ],
            177 => [
                'id' => 178,
                'type' => 'ស្រុក',
                'code' => '2101',
                'name_kh' => 'អង្គរបូរី',
                'name_en' => 'Angkor Borei',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            178 => [
                'id' => 179,
                'type' => 'ស្រុក',
                'code' => '2102',
                'name_kh' => 'បាទី',
                'name_en' => 'Bati',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            179 => [
                'id' => 180,
                'type' => 'ស្រុក',
                'code' => '2103',
                'name_kh' => 'បូរីជលសារ',
                'name_en' => 'Borei Cholsar',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            180 => [
                'id' => 181,
                'type' => 'ស្រុក',
                'code' => '2104',
                'name_kh' => 'គីរីវង់',
                'name_en' => 'Kiri Vong',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            181 => [
                'id' => 182,
                'type' => 'ស្រុក',
                'code' => '2105',
                'name_kh' => 'កោះអណ្ដែត',
                'name_en' => 'Kaoh Andaet',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            182 => [
                'id' => 183,
                'type' => 'ស្រុក',
                'code' => '2106',
                'name_kh' => 'ព្រៃកប្បាស',
                'name_en' => 'Prey Kabbas',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            183 => [
                'id' => 184,
                'type' => 'ស្រុក',
                'code' => '2107',
                'name_kh' => 'សំរោង',
                'name_en' => 'Samraong',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            184 => [
                'id' => 185,
                'type' => 'ក្រុង',
                'code' => '2108',
                'name_kh' => 'ដូនកែវ',
                'name_en' => 'Doun Kaev',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            185 => [
                'id' => 186,
                'type' => 'ស្រុក',
                'code' => '2109',
                'name_kh' => 'ត្រាំកក់',
                'name_en' => 'Tram Kak',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            186 => [
                'id' => 187,
                'type' => 'ស្រុក',
                'code' => '2110',
                'name_kh' => 'ទ្រាំង',
                'name_en' => 'Treang',
                'province_id' => 21,
                'created_at' => null,
                'updated_at' => null,
            ],
            187 => [
                'id' => 188,
                'type' => 'ស្រុក',
                'code' => '2201',
                'name_kh' => 'អន្លង់វែង',
                'name_en' => 'Anlong Veaeng',
                'province_id' => 22,
                'created_at' => null,
                'updated_at' => null,
            ],
            188 => [
                'id' => 189,
                'type' => 'ស្រុក',
                'code' => '2202',
                'name_kh' => 'បន្ទាយអំពិល',
                'name_en' => 'Banteay Ampil',
                'province_id' => 22,
                'created_at' => null,
                'updated_at' => null,
            ],
            189 => [
                'id' => 190,
                'type' => 'ស្រុក',
                'code' => '2203',
                'name_kh' => 'ចុងកាល់',
                'name_en' => 'Chong Kal',
                'province_id' => 22,
                'created_at' => null,
                'updated_at' => null,
            ],
            190 => [
                'id' => 191,
                'type' => 'ក្រុង',
                'code' => '2204',
                'name_kh' => 'សំរោង',
                'name_en' => 'Samraong',
                'province_id' => 22,
                'created_at' => null,
                'updated_at' => null,
            ],
            191 => [
                'id' => 192,
                'type' => 'ស្រុក',
                'code' => '2205',
                'name_kh' => 'ត្រពាំងប្រាសាទ',
                'name_en' => 'Trapeang Prasat',
                'province_id' => 22,
                'created_at' => null,
                'updated_at' => null,
            ],
            192 => [
                'id' => 193,
                'type' => 'ស្រុក',
                'code' => '2301',
                'name_kh' => 'ដំណាក់ចង្អើរ',
                'name_en' => 'Damnak Chang\'aeur',
                'province_id' => 23,
                'created_at' => null,
                'updated_at' => null,
            ],
            193 => [
                'id' => 194,
                'type' => 'ក្រុង',
                'code' => '2302',
                'name_kh' => 'កែប',
                'name_en' => 'Kaeb',
                'province_id' => 23,
                'created_at' => null,
                'updated_at' => null,
            ],
            194 => [
                'id' => 195,
                'type' => 'ក្រុង',
                'code' => '2401',
                'name_kh' => 'ប៉ៃលិន',
                'name_en' => 'Pailin',
                'province_id' => 24,
                'created_at' => null,
                'updated_at' => null,
            ],
            195 => [
                'id' => 196,
                'type' => 'ស្រុក',
                'code' => '2402',
                'name_kh' => 'សាលាក្រៅ',
                'name_en' => 'Sala Krau',
                'province_id' => 24,
                'created_at' => null,
                'updated_at' => null,
            ],
            196 => [
                'id' => 197,
                'type' => 'ស្រុក',
                'code' => '2501',
                'name_kh' => 'តំបែរ',
                'name_en' => 'Dambae',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            197 => [
                'id' => 198,
                'type' => 'ស្រុក',
                'code' => '2502',
                'name_kh' => 'ក្រូចឆ្មារ',
                'name_en' => 'Krouch Chhmar',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            198 => [
                'id' => 199,
                'type' => 'ស្រុក',
                'code' => '2503',
                'name_kh' => 'មេមត់',
                'name_en' => 'Memot',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            199 => [
                'id' => 200,
                'type' => 'ស្រុក',
                'code' => '2504',
                'name_kh' => 'អូររាំងឪ',
                'name_en' => 'Ou Reang Ov',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            200 => [
                'id' => 201,
                'type' => 'ស្រុក',
                'code' => '2505',
                'name_kh' => 'ពញាក្រែក',
                'name_en' => 'Ponhea Kraek',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            201 => [
                'id' => 202,
                'type' => 'ក្រុង',
                'code' => '2506',
                'name_kh' => 'សួង',
                'name_en' => 'Suong',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
            202 => [
                'id' => 203,
                'type' => 'ស្រុក',
                'code' => '2507',
                'name_kh' => 'ត្បូងឃ្មុំ',
                'name_en' => 'Tboung Khmum',
                'province_id' => 25,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);

    }
}
