<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProvincesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('provinces')->delete();

        \DB::table('provinces')->insert([
            0 => [
                'id' => 1,
                'type' => 'ខេត្ត​',
                'code' => '1',
                'name_kh' => 'បន្ទាយមានជ័យ',
                'name_en' => 'Banteay Meanchey',
                'created_at' => null,
                'updated_at' => null,
            ],
            1 => [
                'id' => 2,
                'type' => 'ខេត្ត​',
                'code' => '2',
                'name_kh' => 'បាត់ដំបង',
                'name_en' => 'Battambang',
                'created_at' => null,
                'updated_at' => null,
            ],
            2 => [
                'id' => 3,
                'type' => 'ខេត្ត​',
                'code' => '3',
                'name_kh' => 'កំពង់ចាម',
                'name_en' => 'Kampong Cham',
                'created_at' => null,
                'updated_at' => null,
            ],
            3 => [
                'id' => 4,
                'type' => 'ខេត្ត​',
                'code' => '4',
                'name_kh' => 'កំពង់ឆ្នាំង',
                'name_en' => 'Kampong Chhnang',
                'created_at' => null,
                'updated_at' => null,
            ],
            4 => [
                'id' => 5,
                'type' => 'ខេត្ត​',
                'code' => '5',
                'name_kh' => 'កំពង់ស្ពឺ',
                'name_en' => 'Kampong Speu',
                'created_at' => null,
                'updated_at' => null,
            ],
            5 => [
                'id' => 6,
                'type' => 'ខេត្ត​',
                'code' => '6',
                'name_kh' => 'កំពង់ធំ',
                'name_en' => 'Kampong Thom',
                'created_at' => null,
                'updated_at' => null,
            ],
            6 => [
                'id' => 7,
                'type' => 'ខេត្ត​',
                'code' => '7',
                'name_kh' => 'កំពត',
                'name_en' => 'Kampot',
                'created_at' => null,
                'updated_at' => null,
            ],
            7 => [
                'id' => 8,
                'type' => 'ខេត្ត​',
                'code' => '8',
                'name_kh' => 'កណ្ដាល',
                'name_en' => 'Kandal',
                'created_at' => null,
                'updated_at' => null,
            ],
            8 => [
                'id' => 9,
                'type' => 'ខេត្ត​',
                'code' => '9',
                'name_kh' => 'កោះកុង',
                'name_en' => 'Koh Kong',
                'created_at' => null,
                'updated_at' => null,
            ],
            9 => [
                'id' => 10,
                'type' => 'ខេត្ត​',
                'code' => '10',
                'name_kh' => 'ក្រចេះ',
                'name_en' => 'Kratie',
                'created_at' => null,
                'updated_at' => null,
            ],
            10 => [
                'id' => 11,
                'type' => 'ខេត្ត​',
                'code' => '11',
                'name_kh' => 'មណ្ឌលគិរី',
                'name_en' => 'Mondul Kiri',
                'created_at' => null,
                'updated_at' => null,
            ],
            11 => [
                'id' => 12,
                'type' => 'ខេត្ត​',
                'code' => '12',
                'name_kh' => 'រាជធានីភ្នំពេញ',
                'name_en' => 'Phnom Penh',
                'created_at' => null,
                'updated_at' => null,
            ],
            12 => [
                'id' => 13,
                'type' => 'ខេត្ត​',
                'code' => '13',
                'name_kh' => 'ព្រះវិហារ',
                'name_en' => 'Preah Vihear',
                'created_at' => null,
                'updated_at' => null,
            ],
            13 => [
                'id' => 14,
                'type' => 'ខេត្ត​',
                'code' => '14',
                'name_kh' => 'ព្រៃវែង	',
                'name_en' => 'Prey Veng',
                'created_at' => null,
                'updated_at' => null,
            ],
            14 => [
                'id' => 15,
                'type' => 'ខេត្ត​',
                'code' => '15',
                'name_kh' => 'ពោធិ៍សាត់	',
                'name_en' => 'Pursat',
                'created_at' => null,
                'updated_at' => null,
            ],
            15 => [
                'id' => 16,
                'type' => 'ខេត្ត​',
                'code' => '16',
                'name_kh' => 'រតនគិរី	',
                'name_en' => 'Ratanak Kiri',
                'created_at' => null,
                'updated_at' => null,
            ],
            16 => [
                'id' => 17,
                'type' => 'ខេត្ត​',
                'code' => '17',
                'name_kh' => 'សៀមរាប	',
                'name_en' => 'Siemreap',
                'created_at' => null,
                'updated_at' => null,
            ],
            17 => [
                'id' => 18,
                'type' => 'ខេត្ត​',
                'code' => '18',
                'name_kh' => 'ព្រះសីហនុ	',
                'name_en' => 'Preah Sihanouk',
                'created_at' => null,
                'updated_at' => null,
            ],
            18 => [
                'id' => 19,
                'type' => 'ខេត្ត​',
                'code' => '19',
                'name_kh' => 'ស្ទឹងត្រែង	',
                'name_en' => 'Stung Treng',
                'created_at' => null,
                'updated_at' => null,
            ],
            19 => [
                'id' => 20,
                'type' => 'ខេត្ត​',
                'code' => '20',
                'name_kh' => 'ស្វាយរៀង	',
                'name_en' => 'Svay Rieng',
                'created_at' => null,
                'updated_at' => null,
            ],
            20 => [
                'id' => 21,
                'type' => 'ខេត្ត​',
                'code' => '21',
                'name_kh' => 'តាកែវ	',
                'name_en' => 'Takeo',
                'created_at' => null,
                'updated_at' => null,
            ],
            21 => [
                'id' => 22,
                'type' => 'ខេត្ត​',
                'code' => '22',
                'name_kh' => 'ឧត្ដរមានជ័យ	',
                'name_en' => 'Oddar Meanchey',
                'created_at' => null,
                'updated_at' => null,
            ],
            22 => [
                'id' => 23,
                'type' => 'ខេត្ត​',
                'code' => '23',
                'name_kh' => 'កែប	',
                'name_en' => 'Kep',
                'created_at' => null,
                'updated_at' => null,
            ],
            23 => [
                'id' => 24,
                'type' => 'ខេត្ត​',
                'code' => '24',
                'name_kh' => 'ប៉ៃលិន	',
                'name_en' => 'Pailin',
                'created_at' => null,
                'updated_at' => null,
            ],
            24 => [
                'id' => 25,
                'type' => 'ខេត្ត​',
                'code' => '25',
                'name_kh' => 'ត្បូងឃ្មុំ	',
                'name_en' => 'Tboung Khmum',
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);

    }
}
