<?php
use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'throttle:admin']], function () {
  Route::get('/', function () {
    return redirect()->route('admin.dashboard');
  });
  Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard');
  Route::get('permissions/changeStatus', [App\Http\Controllers\Admin\PermissionController::class, 'changeStatus'])->name('permissions.changeStatus');
  Route::resource('permissions', App\Http\Controllers\Admin\PermissionController::class)->except('create', 'update');
  Route::get('roles/changeStatus', [App\Http\Controllers\Admin\RoleController::class, 'changeStatus'])->name('roles.changeStatus');
  Route::resource('roles', App\Http\Controllers\Admin\RoleController::class)->except('create', 'update');
  Route::get('users/changeStatus', [App\Http\Controllers\Admin\UserController::class, 'changeStatus'])->name('users.changeStatus');
  Route::resource('users', App\Http\Controllers\Admin\UserController::class)->except('create', 'update');
  Route::get('customers/changeStatus', [App\Http\Controllers\Admin\CustomerController::class, 'changeStatus'])->name('customers.changeStatus');
  Route::resource('customers', App\Http\Controllers\Admin\CustomerController::class)->except('create', 'update');
  Route::get('item_groups/changeStatus', [App\Http\Controllers\Admin\ItemGroupController::class, 'changeStatus'])->name('item_groups.changeStatus');
  Route::resource('item_groups', App\Http\Controllers\Admin\ItemGroupController::class)->except('create', 'update');
  Route::get('item_types/changeStatus', [App\Http\Controllers\Admin\ItemTypeController::class, 'changeStatus'])->name('item_types.changeStatus');
  Route::resource('item_types', App\Http\Controllers\Admin\ItemTypeController::class)->except('create', 'update');
  Route::get('items/changeStatus', [App\Http\Controllers\Admin\ItemController::class, 'changeStatus'])->name('items.changeStatus');
  Route::resource('items', App\Http\Controllers\Admin\ItemController::class)->except('create', 'update');
  Route::get('lifesigns/changeStatus', [App\Http\Controllers\Admin\LifeSignController::class, 'changeStatus'])->name('lifesigns.changeStatus');
  Route::resource('lifesigns', App\Http\Controllers\Admin\LifeSignController::class)->except('create', 'update');
  Route::controller(App\Http\Controllers\Admin\DocumentController::class)->group(function () {
    Route::get('documents/changeStatus', 'changeStatus')->name('documents.changeStatus');
    Route::get('documents/gotoService/document={document}/customer={customer}', 'gotoService')->name('documents.gotoService');
    Route::get('documents/getCustomer', 'getCustomer')->name('documents.getCustomer');
    Route::get('documents/getLifeSign', 'getLifeSign')->name('documents.getLifeSign');
    Route::get('documents/getBio', 'getBio')->name('documents.getBio');
    Route::get('documents/getGroupType', 'getGroupType')->name('documents.getGroupType');
    Route::get('documents/getItemTypeByName', 'getItemTypeByName')->name('documents.getItemTypeByName');
    Route::get('documents/getBioAnalystForm', 'getBioAnalystForm')->name('documents.getBioAnalystForm');
    Route::post('documents/storeBio', 'storeBio')->name('documents.storeBio');
    Route::get('documents/getPBio', 'getPBio')->name('documents.getPBio');
    Route::post('documents/storePBio', 'storePBio')->name('documents.storePBio');
    Route::post('documents/deletePBio', 'deletePBio')->name('documents.deletePBio');
    Route::get('documents/getMore', 'getMore')->name('documents.getMore');
    Route::post('documents/storeDoctorOrder', 'storeDoctorOrder')->name('documents.storeDoctorOrder');
    Route::post('documents/storeRx', 'storeRx')->name('documents.storeRx');
    Route::get('documents/getRx', 'getRx')->name('documents.getRx');
    Route::get('documents/editRxDetail', 'editRxDetail')->name('documents.editRxDetail');
    Route::post('documents/updateRxNurse', 'updateRxNurse')->name('documents.updateRxNurse');
    Route::get('documents/getRxDetail', 'getRxDetail')->name('documents.getRxDetail');
    Route::get('documents/showtRxDetail', 'showtRxDetail')->name('documents.showtRxDetail');
    Route::post('documents/deleteFile', 'deleteFile')->name('documents.deleteFile');
    Route::get('documents/pdfPreview/{id}', 'pdfPreview')->name('documents.pdfPreview');
    Route::get('documents/getNurseDetail', 'getNurseDetail')->name('documents.getNurseDetail');
    Route::post('documents/frmAddNewRxNurse', 'frmAddNewRxNurse')->name('documents.frmAddNewRxNurse');
    Route::get('documents/hospital/{customer}/{document}/show', 'showHospital')->name('documents.show.hospital');
    Route::get('documents/getObjectH', 'getObjectH')->name('documents.getObjectH');
    Route::post('documents/storeObjectH', 'storeObjectH')->name('documents.storeObjectH');
    Route::post('documents/storeObjectHT', 'storeObjectHT')->name('documents.storeObjectHT');
    Route::get('documents/editObjectHT', 'editObjectHT')->name('documents.editObjectHT');
    Route::post('documents/deleteObjectHT', 'deleteObjectHT')->name('documents.deleteObjectHT');
    Route::post('documents/deleteObjectHTD', 'deleteObjectHTD')->name('documents.deleteObjectHTD');
    Route::post('documents/storeObjectHNote', 'storeObjectHNote')->name('documents.storeObjectHNote');
    Route::get('documents/editObjectHNote', 'editObjectHNote')->name('documents.editObjectHNote');
    Route::post('documents/deleteObjectHNote', 'deleteObjectHNote')->name('documents.deleteObjectHNote');
    Route::post('documents/updateObjectHNote', 'updateObjectHNote')->name('documents.updateObjectHNote');
    Route::post('documents/storeDocumentLife', 'storeDocumentLife')->name('documents.documentlife.store');
    Route::post('documents/storeObjectOrder', 'storeObjectOrder')->name('documents.storeObjectOrder');
    Route::post('documents/storeObjectInjection', 'storeObjectInjection')->name('documents.storeObjectInjection');
    Route::get('documents/getObjectOrder', 'getObjectOrder')->name('documents.getObjectOrder');
    Route::get('documents/order/getProductByID', 'getProductByID')->name('documents.getProductByID');
    Route::get('documents/{order}/previewReceipt', 'previewReceipt')->name('documents.previewReceipt');
    Route::get('documents/search_how_to_use', 'search_how_to_use')->name('documents.search_how_to_use');
    Route::post('documents/checkout', 'checkout')->name('documents.checkout');
    Route::post('documents/customer/storeCustomer', 'storeCustomer')->name('documents.storeCustomer');
    Route::get('documents/doclife/editDocumentLife', 'editDocumentLife')->name('documents.editDocumentLife');
    Route::post('documents/updateDocumentLife', 'updateDocumentLife')->name('documents.updateDocumentLife');
    Route::get('documents/bioReceipt/Customer={customer_id}/Document={document_id}', 'bioReceipt')->name('documents.bio.receipt');
    Route::post('documents/filterTreatment', 'filterTreatment')->name('documents.filterTreatment');
    Route::get('documents/order/search_product', 'searchProduct')->name('documents.searchProduct');
    Route::post('documents/order/removeOrder', 'removeOrder')->name('documents.removeOrder');
    Route::post('documents/order/removeInjection', 'removeInjection')->name('documents.removeInjection');
  });
  Route::resource('documents', App\Http\Controllers\Admin\DocumentController::class)->except('create', 'update');
  Route::get('document_lives/changeStatus', [App\Http\Controllers\Admin\DocumentLifeController::class, 'changeStatus'])->name('document_lives.changeStatus');
  Route::resource('document_lives', App\Http\Controllers\Admin\DocumentLifeController::class)->except('create', 'update');
  Route::get('document_life_details/changeStatus', [App\Http\Controllers\Admin\DocumentLifeDetailController::class, 'changeStatus'])->name('document_life_detail.changeStatus');
  Route::resource('document_life_details', App\Http\Controllers\Admin\DocumentLifeDetailController::class)->except('create', 'update');
  Route::get('products/changeStatus', [App\Http\Controllers\Admin\ProductController::class, 'changeStatus'])->name('products.changeStatus');
  Route::post('products/storeOrder', [App\Http\Controllers\Admin\ProductController::class, 'storeNew'])->name('products.storeNew');
  Route::resource('products', App\Http\Controllers\Admin\ProductController::class)->except('create', 'update');
  Route::get('rooms/changeStatus', [App\Http\Controllers\Admin\RoomController::class, 'changeStatus'])->name('rooms.changeStatus');
  // Route::get('rooms/getParameeters/{param1}/{param2}',[App\Http\Controllers\Admin\RoomController::class,'getParameeters'])->name('rooms.getParameeters');
  Route::resource('rooms', App\Http\Controllers\Admin\RoomController::class)->except('create', 'update');
  Route::controller(App\Http\Controllers\Admin\CustomerHistory::class)->group(function () {
    Route::get('histories/showHistory', 'showHistory')->name('histories.showHistory');
    Route::get('histories/customer={customer}/detail', 'detail')->name('histories.detail');
    Route::get('histories/customerDetail', 'customerDetail')->name('histories.customerDetail');
    Route::get('histories/customer={customer}/document={document}/detail', 'documentDetail')->name('histories.documentDetail');
    Route::get('histories/order={order}/previewReceipt', 'previewReceipt')->name('histories.previewReceipt');
    Route::get('histories/showtRxDetail', 'showtRxDetail')->name('histories.showtRxDetail');
    Route::get('histories/Customer={customer}/serviceDetail', 'serviceDetail')->name('histories.serviceDetail');
    Route::get('histories/changeStatus', 'changeStatus')->name('histories.changeStatus');
    Route::get('customers/all/orders', 'order')->name('customers.order');
  });
  Route::controller(App\Http\Controllers\Admin\OperativeController::class)->group(function () {
    Route::get('documents/{OperativeProtocol}/receiptProtocol', 'receiptProtocol')->name('documents.receiptProtocol');
    Route::post('documents/storeProtocol', 'storeProtocol')->name('documents.storeProtocol');
    Route::get('documents/{MedicalCertificate}/receiptMedicine', 'receiptMedicine')->name('documents.receiptMedicine');
    Route::post('documents/storeMedicine', 'storeMedicine')->name('documents.storeMedicine');
  });

  Route::get('schedules/showCalendar', [App\Http\Controllers\Admin\ScheduleController::class, 'showCalendar'])->name('schedules.showCalendar');
  Route::get('schedules/showScheduleDocument/{schedule}', [App\Http\Controllers\Admin\ScheduleController::class, 'showScheduleDocument'])->name('schedules.showScheduleDocument');
  Route::get('schedules/detail/document/{document_id}/{customer_id}', [App\Http\Controllers\Admin\ScheduleController::class, 'showDetailByDocument'])->name('schedules.showDetailByDocument');

  Route::resource('schedules', App\Http\Controllers\Admin\ScheduleController::class);

  Route::get('company_informations/changeStatus', [App\Http\Controllers\Admin\CompanyInformationController::class, 'changeStatus'])->name('company_informations.changeStatus');
  Route::resource('company_informations', App\Http\Controllers\Admin\CompanyInformationController::class)->except('create', 'update');
});
