<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Non-Conformance Reports (NCR) and Corrective / Preventive Actions
 * (CAPA).
 *
 * ISO 9001:2015 §10.2 ("Nonconformity and corrective action") and
 * ISO 15189:2022 §8.7 ("Nonconformities") require:
 *   - A formal record of every nonconformity, with severity.
 *   - Immediate containment action.
 *   - A documented CAPA workflow with root-cause analysis,
 *     planned action, and an effectiveness check before closure.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('non_conformances', function (Blueprint $table) {
            $table->id();

            // Human-friendly reference, e.g. "NCR-2026-0007". Owned and
            // generated by App\Services\NcrReferenceService (to be added
            // in Phase 4 alongside the controller split — for now the
            // model layer accepts whatever code the caller provides).
            $table->string('code', 64)->unique();

            $table->string('title', 255);
            $table->longText('description');
            $table->text('immediate_action')->nullable();

            // Source the NCR was raised from.
            // internal_audit / external_audit / customer_complaint /
            // incident / proficiency_test / management_review / other
            $table->string('source', 32);

            // low / medium / high / critical
            $table->string('severity', 16);

            // open / under_investigation / closed_no_action / closed_with_capa
            $table->string('status', 32)->default('open');

            $table->foreignId('reported_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('reported_at')->useCurrent();
            $table->timestamp('closed_at')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('deleted_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('capa_actions', function (Blueprint $table) {
            $table->id();
            $table->foreignId('non_conformance_id')->constrained('non_conformances')->cascadeOnDelete();

            // corrective (fix what already happened) /
            // preventive (stop recurrence)
            $table->string('action_type', 16);

            $table->text('root_cause')->nullable();
            $table->text('action_plan');
            $table->text('action_taken')->nullable();
            $table->text('verification_evidence')->nullable();

            $table->foreignId('assignee_id')->nullable()->constrained('users')->nullOnDelete();
            $table->date('due_at')->nullable();

            // open / in_progress / effectiveness_check / closed / cancelled
            $table->string('status', 32)->default('open');

            $table->foreignId('closed_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('closed_at')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();
            $table->foreignId('deleted_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('capa_actions');
        Schema::dropIfExists('non_conformances');
    }
};
